import type { Metadata } from 'next'
import { Inria_Sans as Inria } from 'next/font/google'
import './globals.css'
import { cn } from '@/lib/utils'
import Navbar from '@/components/Navbar'

const inria = Inria({ weight: '400', style: 'normal', subsets: ['latin'] })

export const metadata: Metadata = {
  title: 'EasyBill',
  description: 'Generated by create next app',
}

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode
}>) {
  return (
    <html lang="en">
      <body className={cn('font-sans antialiased', inria.className)}>
        <main className="mx-auto grid w-full bg-background">
          <Navbar />
          <div>{children}</div>
        </main>
      </body>
    </html>
  )
}
